export interface Member{
  clientType: string;
  productName: string;
  planName: string;
  memberId: string;
    id:"";
	relations:"";
	employeeId:"";
	name:"";
	dateOfBirth:0;
	age:0;
	gender:"";
	email:"";
	mobileNo:"";
	memberAddressLine1:"";
	memberAddressLine2:"";
	designation:"";
	unit:"";
	department:"";
	postalCode:"";
	identificationDocType:"";
	identificationDocNumber:"";
	planScheme:"";
	membershipNo:"";
	nomineeName:"";
	nomineeRelation:"";
	nomineeDob:"";
	dateOfJoining:"";
	eftDetails:"";
	bankName:"";
	bankBranchCode:"";
	accountName:"";
	accountNo:"";
	ifscCode:"";
	employeeName:"";
	familySize:"";
	processRequestId:"";
	prospectId:"";
	policyNumber:"";
	policyStartDate:0;
	policyEndDate:0;
}
